#!/usr/bin/env python

import sys
import curses
import curses.panel
from MegaApp import MegaApp


def main(stdscr):
    y, x = stdscr.getmaxyx()

    stdscr.keypad(True)
    pos_y = 4

    app = MegaApp(y, x, sys.argv)

    stdscr.addstr(8, 0, "                                                                                      ")
    stdscr.addstr(8, 0, str(app.tabBar.tab_titles))

    while True:
        ch = stdscr.getch()

        if ch == 24:
            break
        elif ch == 558:
            # switch to next tab...alt + right
            app.tabBar.nextTab()
        elif ch == 543:
            # switch to prev tab...alt + left
            app.tabBar.prevTab()
        elif ch == 14:
            # add new tab...ctrl + n
            app.tabBar.addTab()
        elif ch == 88 or ch == 120:
            # delete active tab...alt + x / alt + X
            app.tabBar.closeTab()

        stdscr.addstr(7, 0, "Typed key :         ")
        stdscr.addstr(7, 0, "Typed key : "+str(ch))
        stdscr.addstr(8, 0, "                                                                                      ")
        stdscr.addstr(8, 0, str(app.tabBar.active_tab))
        pos_y += 1

    curses.endwin()


if __name__ == '__main__':
    curses.wrapper(main)